### ISSUE TITLE
Do you have any test user accounts for parents, childs, merchants?

### ISSUE THREAD

**Issue by KumarKumarc123** [VirtualPiggyInc/oink_unity3d#1]
Hi,

I am not able to test Oink plugin for Unity. Please provide some test merchant, parent, child accounts if any.

**Comment by ekovshilovsky** [comment]
In order to test our plugin, you will need to be setup as a merchant and I would need a lot more information.  Would you mind filling out a contact and information form at http://developer.oink.com/sign-up/ and I will make sure one of our integration people contacts you so we can help you setup your test environment.
